apiVersion: v1
kind: Secret
metadata:
    name: skald-worker-secrets
    namespace: skald
    labels:
        app: skald-worker
type: Opaque
stringData:
    # Skald API Key
    SKALD_API_KEY: ''

    # Jira Credentials
    JIRA_SERVER: ''
    JIRA_USER: ''
    JIRA_PASSWORD: ''

    # SPMS/Docs API
    SPMS_BASE_URL: 'http://spms.sparrow.local'
