apiVersion: v1
kind: Service
metadata:
    name: discord-bot-service
    namespace: skald
    labels:
        app: skald
        component: discord-bot
spec:
    type: ClusterIP
    ports:
        - name: http
          port: 3000
          targetPort: 3000
          protocol: TCP
    selector:
        component: discord-bot
